### PR TITLE
fix: fix fallback to last cached tags

### LINKED ISSUE #615: Error taking last tags
About this line https://github.com/maxbrunet/prometheus-elasticache-sd/blob/main/main.go#L201
it should be 
```diff
- if _, ok := d.lastTags[*cc.ARN]; !ok {
+ if _, ok := d.lastTags[*cc.ARN]; ok {
```

### PR DESCRIPTION
**Pull request by gavin-jeong**
Fix #615

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -198,7 +198,7 @@ func (d *ElasticacheDiscovery) refresh(ctx context.Context) ([]*targetgroup.Grou
 				// its tags are unavailable, so if the relabeling logic depends on `__meta_elasticache_tag_<tagkey>` labels,
 				// the clusters may disappear from the Prometheus targets when that happens,
 				// thus we try to reuse the last tags we know about.
-				if _, ok := d.lastTags[*cc.ARN]; !ok {
+				if _, ok := d.lastTags[*cc.ARN]; ok {
 					level.Warn(d.logger).Log("msg", "reusing last known tags", "err", err.Error(), "ARN", *cc.ARN)
```
Comment (maxbrunet) [inline main.go:202]: Not sure why there is an error field here either

```suggestion
					level.Warn(d.logger).Log("msg", "reusing last known tags", "ARN", *cc.ARN)
```

**Review by maxbrunet — APPROVED** [review]
Good catch, thank you!
